### ISSUE TITLE
adding a DTD link ?

### ISSUE THREAD

**Issue by neywen** [mat007/xeumeuleu#15]
Hi Mat,

Thanks for xeumeuleu, it's great !
I've been trying to look for a way to include a DTD link into an xml output string.
Could not find any hint in the documentation. 
Am I missing something ?

Thanks for any tip,
cheers,
loïc b :)

**Comment by neywen** [comment]
right ! I believe this is simple enough to not require another API update, thanks for the tip.

I'm having difficulties to handle the xml::xostreamstream, though. I look at the sources, and I don't understand how I can output it to a string or a file. I guess I'm blind....

**Comment by mat007** [comment]
xml::xostreamstream simply adapts an std::ostream so either an std::stringstream or an std::ofstream.
I updated the example in my previous comment to provide a more comprehensive example for outputting to a string,
Similarly for a file this would look like
```
    std::ofstream os( "some_file.xml" );
    os << "<!DOCTYPE element SYSTEM 'some_document_type.dtd'>\n";
    xml::xostreamstream xos( os );
    xos << xml::start( "element" ) << xml::end;
```

**Comment by neywen** [comment]
thanks for the help, Mat !
