### ISSUE TITLE
Wiki is down

### ISSUE THREAD

**Issue by poukill** [mat007/xeumeuleu#20]
Hi Mat,

Impossible to reach your wiki yesterday and today as well.
http://xeumeuleu.sourceforge.net/wiki/ displays abnormal page.

Could you look into it ?
Do you have another way to access a Xeumeuleu tutorial ?

Bonne journée et merci d'avance Mat !
++

**Comment by mat007** [comment]
Hey !

Sorry about that, I'll look into it right away.
I hope the pages haven't been lost, I'm not sure when was the last backup made…

Bonne journée aussi !

**Comment by mat007** [comment]
It seems I am able to reach it now, I suppose it must have been some sourceforge hosting glitch…
Does it work for you too now?

**Comment by poukill** [comment]
![xeumeuleu](https://user-images.githubusercontent.com/3787856/36473936-565d4d62-16f6-11e8-8a6f-01725a4d7737.png)

Non ça ne marche toujours pas... cf capture d'écran... Ca marche chez toi ?
J'ai testé avec Chrome et IE.

**Comment by mat007** [comment]
Oui avec firefox ça semble OK…
Pas mieux avec ctrl-F5 ?

**Comment by poukill** [comment]
Nope. J'ai essayé avec Chrome, Firefox et IE.
Sur mon smartphone avec Chrome, pareil, en Wifi ou 4G...
Hier c'était pareil. Bigre ! Bizarre que ça marche chez toi.

**Comment by mat007** [comment]
Et directement http://xeumeuleu.sourceforge.net/wiki/index.php/Welcome ?

**Comment by mat007** [comment]
OK, tu m'as fait activer IE mais j'arrive à le reproduire avec… :)

**Comment by mat007** [comment]
Et avec firefox aussi maintenant que je me suis déconnecté…
Bon j'ai ouvert un ticket chez sourceforge https://sourceforge.net/p/forge/site-support/16534/ mais je vais regarder un peu de mon côté aussi.

**Comment by poukill** [comment]
Hier de temps à autre, j'avais un message plus clair qu'aujourd'hui. Un problème de droit sur un fichier propre à MediaWiki 1.23.1. Mais je n'arrive pas à reproduire aujourd'hui sinon je te l'aurais mentionné.

**Comment by mat007** [comment]
En effet je l'ai eu aussi et j'ai corrigé les droits du coup…

**Comment by mat007** [comment]
C'est corrigé, merci à toi !

**Comment by poukill** [comment]
Cool, au boulot alors !
Merci pour ta réactivité ! :)
