### ISSUE TITLE
Tag <!DOCTYPE TS> throw

### ISSUE THREAD

**Issue by AdrienUfferte** [mat007/xeumeuleu#25]
The following test fails if the root name specified after !DOCTYPE is the same as the first following tag.

```
BOOST_AUTO_TEST_CASE( test )
{
  std::string test(
    "<?xml version='1.0' encoding='utf-8'?>"
    "<!DOCTYPE TS>"
    "<TS version='2.0' language='pt' sourcelanguage='en'>"
    "<context>";
  xml::xistringstream xis( test );
  BOOST_CHECK_NO_THROW( xis >> xml::start( "TS") >> xml::start( "context"); );
}
```

The error thrown is approximately "TS has no child named 'context'".

For example,
```
    "<!DOCTYPE TS>"
    "<TS version='2.0' language='pt' sourcelanguage='en'>"
    "<context>";
```
throws when we call xis << xml::start( "context" );

But:
```
    "<!DOCTYPE TS>"
    "<TDS version='2.0' language='pt' sourcelanguage='en'>"
    "<context>";
```
Does not throw.

Same with html, etc...

**Comment by mat007** [comment]
Sorry I don’t quite understand what you mean.
Can you show a test which fails but in your opinion should pass (i.e. the test that should be added in order to fix the code)?

Thanks!

**Comment by AdrienUfferte** [comment]
This test throws but shouldn't :
```
BOOST_AUTO_TEST_CASE( test )
{
  std::string test(
    "<?xml version='1.0' encoding='utf-8'?>"
    "<!DOCTYPE TS>"
    "<TS version='2.0' language='pt' sourcelanguage='en'>"
    "<context>";
  xml::xistringstream xis( test );
  BOOST_CHECK_NO_THROW( xis >> xml::start( "TS") >> xml::start( "context"); );
}
```

**Comment by mat007** [comment]
I’m surprised it doesn’t throw earlier as this is not valid XML, but I’ll assume the missing end tags are a typo.

I don’t think there is any special handling in xeumeuleu itself regarding DTD as it’s merely a wrapper around Xerces, therefore I’m afraid it’s likely an issue in Xerces itself…

**Comment by AdrienUfferte** [comment]
Ok thanks.
